// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RollDx(arg1) {
  return window['go']['dice']['DiceRoller']['RollDx'](arg1);
}

export function RollMultipleDice(arg1, arg2, arg3) {
  return window['go']['dice']['DiceRoller']['RollMultipleDice'](arg1, arg2, arg3);
}
