// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RollDx(arg1:number):Promise<number>;

export function RollMultipleDice(arg1:number,arg2:number,arg3:number):Promise<Array<number>>;
