// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {investigator} from '../models';
import {utils} from '../models';

export function GetCharacteristics():Promise<investigator.Characteristics>;

export function PrintCharacteristics():Promise<void>;

export function UpdateCharacteristics(arg1:utils.Point,arg2:utils.Point,arg3:utils.Point,arg4:utils.Point,arg5:utils.Point,arg6:utils.Point,arg7:utils.Point,arg8:utils.Point):Promise<void>;
