// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCharacteristics() {
  return window['go']['investigator']['Characteristics']['GetCharacteristics']();
}

export function PrintCharacteristics() {
  return window['go']['investigator']['Characteristics']['PrintCharacteristics']();
}

export function UpdateCharacteristics(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['investigator']['Characteristics']['UpdateCharacteristics'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}
