// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetInfo() {
  return window['go']['investigator']['Info']['GetInfo']();
}

export function PrintInfo() {
  return window['go']['investigator']['Info']['PrintInfo']();
}

export function ToBase64() {
  return window['go']['investigator']['Info']['ToBase64']();
}

export function UpdateInfo(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['investigator']['Info']['UpdateInfo'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}
