// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {investigator} from '../models';

export function PrintInfo():Promise<void>;

export function ToBase64():Promise<string>;

export function UpdateInfo(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number,arg7:investigator.Sex,arg8:string):Promise<void>;
