// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddWeapon(arg1, arg2, arg3, arg4) {
  return window['go']['investigator']['Investigator']['AddWeapon'](arg1, arg2, arg3, arg4);
}

export function AddWeaponWithConfig(arg1) {
  return window['go']['investigator']['Investigator']['AddWeaponWithConfig'](arg1);
}

export function ChooseAction(arg1) {
  return window['go']['investigator']['Investigator']['ChooseAction'](arg1);
}

export function GetDamageBonus() {
  return window['go']['investigator']['Investigator']['GetDamageBonus']();
}

export function GetDex() {
  return window['go']['investigator']['Investigator']['GetDex']();
}

export function GetName() {
  return window['go']['investigator']['Investigator']['GetName']();
}

export function GetSkillLevel(arg1) {
  return window['go']['investigator']['Investigator']['GetSkillLevel'](arg1);
}

export function GetSkills() {
  return window['go']['investigator']['Investigator']['GetSkills']();
}

export function InitDamageBonus() {
  return window['go']['investigator']['Investigator']['InitDamageBonus']();
}

export function InitHP() {
  return window['go']['investigator']['Investigator']['InitHP']();
}

export function InitLuck() {
  return window['go']['investigator']['Investigator']['InitLuck']();
}

export function InitMP() {
  return window['go']['investigator']['Investigator']['InitMP']();
}

export function InitMove() {
  return window['go']['investigator']['Investigator']['InitMove']();
}

export function InitSan() {
  return window['go']['investigator']['Investigator']['InitSan']();
}

export function InitTwentiesBaseSkills() {
  return window['go']['investigator']['Investigator']['InitTwentiesBaseSkills']();
}

export function InitWeapons() {
  return window['go']['investigator']['Investigator']['InitWeapons']();
}

export function InitializeTwenties() {
  return window['go']['investigator']['Investigator']['InitializeTwenties']();
}

export function IsAlive() {
  return window['go']['investigator']['Investigator']['IsAlive']();
}

export function IsPlayerControlled() {
  return window['go']['investigator']['Investigator']['IsPlayerControlled']();
}

export function Print() {
  return window['go']['investigator']['Investigator']['Print']();
}

export function PrintLuckAndMP() {
  return window['go']['investigator']['Investigator']['PrintLuckAndMP']();
}

export function PrintSkills() {
  return window['go']['investigator']['Investigator']['PrintSkills']();
}

export function PrintWeapons() {
  return window['go']['investigator']['Investigator']['PrintWeapons']();
}

export function ReceiveDamage(arg1) {
  return window['go']['investigator']['Investigator']['ReceiveDamage'](arg1);
}

export function ResetInvestigator() {
  return window['go']['investigator']['Investigator']['ResetInvestigator']();
}

export function Save() {
  return window['go']['investigator']['Investigator']['Save']();
}

export function SetIsPlayerControlled(arg1) {
  return window['go']['investigator']['Investigator']['SetIsPlayerControlled'](arg1);
}

export function TakeTurn(arg1) {
  return window['go']['investigator']['Investigator']['TakeTurn'](arg1);
}

export function UpdateInvestigator(arg1, arg2, arg3, arg4) {
  return window['go']['investigator']['Investigator']['UpdateInvestigator'](arg1, arg2, arg3, arg4);
}
