// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPossession(arg1, arg2, arg3) {
  return window['go']['investigator']['Possessions']['AddPossession'](arg1, arg2, arg3);
}

export function GetPossession(arg1) {
  return window['go']['investigator']['Possessions']['GetPossession'](arg1);
}

export function GetPossessionsList() {
  return window['go']['investigator']['Possessions']['GetPossessionsList']();
}

export function GetSelf() {
  return window['go']['investigator']['Possessions']['GetSelf']();
}

export function ListPossessions() {
  return window['go']['investigator']['Possessions']['ListPossessions']();
}

export function RemovePossession(arg1, arg2) {
  return window['go']['investigator']['Possessions']['RemovePossession'](arg1, arg2);
}

export function ToJSON() {
  return window['go']['investigator']['Possessions']['ToJSON']();
}

export function UpdatePossessions(arg1) {
  return window['go']['investigator']['Possessions']['UpdatePossessions'](arg1);
}
